spring:
  datasource:
    driver-class-name: com.jdbc.mysql.Driver
    username: root
    password: xxxx
    url: jdbc:mysql://xx.xx.xx.xx:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  context-path: /sell